(function(){
'use strict';
var app=document.getElementById('app');
var state={page:'home', detailId:null, tag:'', period:'30', food:'all'};
var records=[
{id:1,date:'2026-05-11',time:'18:30',food:'卵',amount:1,unit:'g',symptom:true,skin:1,resp:0,digest:0,whole:0,detail:'口の周りに赤みと湿疹が出ました。30分程度で改善。',med:'抗ヒスタミン薬',hospital:'なし',photo:true},
{id:2,date:'2026-05-10',time:'12:20',food:'牛乳',amount:5,unit:'ml',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'問題なく摂取できました。',med:'なし',hospital:'なし',photo:false},
{id:3,date:'2026-05-08',time:'18:00',food:'ピーナッツ',amount:0.5,unit:'g',symptom:true,skin:0,resp:1,digest:0,whole:0,detail:'軽い咳がありました。',med:'なし',hospital:'なし',photo:false},
{id:4,date:'2026-05-06',time:'12:10',food:'卵',amount:0.2,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'症状なし。',med:'なし',hospital:'なし',photo:false},
{id:5,date:'2026-05-03',time:'08:10',food:'牛乳',amount:3,unit:'ml',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'症状なし。',med:'なし',hospital:'なし',photo:false},
{id:6,date:'2026-04-29',time:'18:00',food:'卵',amount:0.5,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'症状なし。',med:'なし',hospital:'なし',photo:false},
{id:7,date:'2026-04-25',time:'07:30',food:'小麦',amount:10,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'問題なし。',med:'なし',hospital:'なし',photo:false}
];
var posts=[
{id:1,name:'ひまわりママ',title:'少量ずつ増やすペースについて',body:'卵を少量ずつ続けています。皆さんはどのくらいの頻度で記録していますか？',tags:['卵','少量摂取','相談'],likes:12,comments:8},
{id:2,name:'そらママ',title:'園での食事について相談です',body:'保育園での説明資料の工夫があれば知りたいです。',tags:['保育園','外食','工夫'],likes:7,comments:5},
{id:3,name:'あんずママ',title:'症状写真はいつ撮っていますか？',body:'軽い赤みのとき、どのタイミングで撮影していますか。',tags:['症状写真','皮膚症状','相談'],likes:4,comments:3}
];
function save(){try{localStorage.setItem('allergy_records_v2',JSON.stringify(records));}catch(e){}}
function load(){try{var r=localStorage.getItem('allergy_records_v2');if(r)records=JSON.parse(r);}catch(e){}}
load();
function h(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function nav(page){state.page=page; if(page!=='detail') state.detailId=null; render(); window.scrollTo(0,0);}
window.nav=nav;
function openDetail(id){state.page='detail';state.detailId=id;render();window.scrollTo(0,0);} window.openDetail=openDetail;
function header(title,sub,back){return '<div class="top">'+(back?'<button class="iconbtn" onclick="nav(\''+back+'\')">‹</button>':'<div><div class="title">'+h(title)+'</div><div class="sub">'+h(sub||'')+'</div></div>')+(back?'<div><div class="title">'+h(title)+'</div></div>':'')+'<button class="pillbtn" onclick="nav(\'settings\')">設定</button></div>';}
function bottom(){var items=[['home','🏠','ホーム'],['records','📝','記録'],['calendar','📅','カレンダー'],['community','💬','掲示板'],['summary','📊','サマリー']];var s='<div class="bottom">';for(var i=0;i<items.length;i++){s+='<button class="nav '+(state.page===items[i][0]?'active':'')+'" onclick="nav(\''+items[i][0]+'\')"><span>'+items[i][1]+'</span>'+items[i][2]+'</button>';}return s+'</div>';}
function latest(n){var arr=records.slice().sort(function(a,b){return (b.date+b.time).localeCompare(a.date+a.time);});return arr.slice(0,n||3);} 
function barData(period,food){var days=parseInt(period||'30',10);var end=new Date('2026-05-11');var start=new Date(end);start.setDate(end.getDate()-days+1);var map={};for(var i=0;i<records.length;i++){var r=records[i];var d=new Date(r.date);if(d>=start&&d<=end&&(food==='all'||r.food===food)){map[r.food]=(map[r.food]||0)+Number(r.amount||0);}}
var data=[];for(var k in map)data.push({label:k,value:Math.round(map[k]*10)/10}); if(!data.length)data=[{label:'記録なし',value:0}]; return data;}
function chartHTML(data,clickable){var max=1;for(var i=0;i<data.length;i++)if(data[i].value>max)max=data[i].value;var s='<div class="bar-wrap" '+(clickable?'onclick="nav(\'summary\')"':'')+'>';for(var j=0;j<data.length;j++){var ht=Math.max(8,Math.round((data[j].value/max)*150));s+='<div class="bar"><i style="height:'+ht+'px"></i><b>'+h(data[j].label)+'</b><em>'+h(data[j].value)+'</em></div>';}return s+'</div>';}
function home(){var s=header('ホーム','食物アレルギー記録');s+='<div class="content"><div class="card hero"><h2>こんにちは、保護者さん</h2><p>今日の摂取記録をすぐに残せます。</p><button class="primary" onclick="nav(\'newRecord\')">＋ 摂取記録</button></div><div class="notice">このアプリは経験共有と記録補助を目的とします。診断・治療・摂取量の判断は必ず主治医に相談してください。</div>';
s+='<div class="card"><div class="link-card"><div class="section-title">過去の摂取サマリー</div><span class="muted">タップで詳細</span></div>'+chartHTML(barData('30','all'),true)+'</div>';
s+='<div class="card"><div class="section-title">最近の記録</div>';var arr=latest(3);for(var i=0;i<arr.length;i++){var r=arr[i];s+='<div class="record" onclick="openDetail('+r.id+')"><h3>'+h(r.date)+' '+h(r.food)+' '+h(r.amount)+h(r.unit)+'</h3><div class="muted">'+(r.symptom?'<span class="danger">症状あり</span>':'<span class="safe">症状なし</span>')+'　'+h(r.detail)+'</div></div>';}
s+='</div></div>'+bottom();return wrap(s);}
function newRecord(){var today='2026-05-11';var s=header('摂取記録を入力','', 'home');s+='<div class="content"><div class="card form"><label>食べた日時</label><input id="date" type="date" value="'+today+'"><input id="time" type="time" value="18:30"><label>食べた食材</label><select id="food"><option>卵</option><option>牛乳</option><option>小麦</option><option>ピーナッツ</option><option>ナッツ</option></select><label>食べた量</label><div class="grid2"><input id="amount" type="number" step="0.1" value="1"><select id="unit"><option>g</option><option>ml</option><option>個</option></select></div><label>症状はありましたか？</label><div class="seg"><button id="noBtn" class="on" onclick="setSym(false)">😊 なし</button><button id="yesBtn" onclick="setSym(true)">😟 あり</button></div><div id="symArea" class="hidden"><label>症状の分類</label>'+grade('皮膚・粘膜','skin')+grade('呼吸器','resp')+grade('消化器','digest')+grade('全身','whole')+'<label>使用した薬</label><div class="checks"><label><input type="checkbox" value="抗ヒスタミン薬">抗ヒスタミン薬</label><label><input type="checkbox" value="気管支拡張薬">気管支拡張薬</label><label><input type="checkbox" value="アドレナリン">アドレナリン</label></div><label>症状写真</label><div class="photo-row"><div class="photo">📷</div><div class="photo">＋</div></div><label>症状の詳細</label><textarea id="detail" placeholder="例：口の周りに赤み"></textarea></div><button class="primary" style="width:100%;margin-top:16px" onclick="addRecord()">保存する</button></div></div>'+bottom();return wrap(s);}
function grade(label,id){return '<div class="grade"><b>'+label+'</b><select id="'+id+'"><option value="0">Grade 0</option><option value="1">Grade 1</option><option value="2">Grade 2</option><option value="3">Grade 3</option></select></div>';}
window.setSym=function(v){document.getElementById('symArea').className=v?'':'hidden';document.getElementById('noBtn').className=v?'':'on';document.getElementById('yesBtn').className=v?'bad':'';};
window.addRecord=function(){var sym=document.getElementById('yesBtn').className.indexOf('bad')>=0;var meds=[];var cs=document.querySelectorAll('.checks input:checked');for(var i=0;i<cs.length;i++)meds.push(cs[i].value);var rec={id:Date.now(),date:val('date'),time:val('time'),food:val('food'),amount:Number(val('amount')),unit:val('unit'),symptom:sym,skin:Number(val('skin')||0),resp:Number(val('resp')||0),digest:Number(val('digest')||0),whole:Number(val('whole')||0),detail:val('detail')||'記録しました。',med:meds.join('、')||'なし',hospital:'なし',photo:sym};records.push(rec);save();openDetail(rec.id);};
function val(id){var el=document.getElementById(id);return el?el.value:'';}
function recordsPage(){var s=header('記録一覧','摂取履歴');s+='<div class="content"><div class="list-tabs"><button class="chip active">すべて</button><button class="chip">症状あり</button><button class="chip">症状なし</button></div><div class="card">';var arr=latest(99);for(var i=0;i<arr.length;i++){var r=arr[i];s+='<div class="record" onclick="openDetail('+r.id+')"><h3>'+h(r.date)+' '+h(r.time)+'　'+h(r.food)+' '+h(r.amount)+h(r.unit)+' <span class="right">›</span></h3><div>'+(r.symptom?'<span class="danger">症状あり</span>':'<span class="safe">症状なし</span>')+(r.photo?'　📷写真あり':'')+'</div><div class="muted">'+h(r.detail)+'</div></div>';}
s+='</div></div>'+bottom();return wrap(s);}
function calendarPage(){var s=header('カレンダー','日付タップで詳細へ');s+='<div class="content"><div class="card"><div class="link-card"><button class="iconbtn">‹</button><div class="section-title">2026年5月</div><button class="iconbtn">›</button></div><table class="calendar"><thead><tr>';['月','火','水','木','金','土','日'].forEach(function(d){s+='<th>'+d+'</th>';});s+='</tr></thead><tbody>';var day=1;for(var w=0;w<5;w++){s+='<tr>';for(var c=0;c<7;c++){if(w===0&&c<4){s+='<td></td>';continue;}if(day>31){s+='<td></td>';continue;}var ds='2026-05-'+(day<10?'0'+day:day);var rec=findByDate(ds);var cls=rec?(rec.symptom?'symptom has':'safe has'):'';s+='<td class="'+cls+'" '+(rec?'onclick="openDetail('+rec.id+')"':'')+'>'+day+'</td>';day++;}s+='</tr>';}s+='</tbody></table><div class="legend"><span>○ 症状なし</span><span>△ 軽症</span><span>× 症状あり</span><span>— 記録なし</span></div></div></div>'+bottom();return wrap(s);}
function findByDate(ds){var arr=records.filter(function(r){return r.date===ds;}).sort(function(a,b){return a.time.localeCompare(b.time);});return arr[0];}
function detailPage(){var arr=latest(999).reverse();var idx=0;for(var i=0;i<arr.length;i++)if(arr[i].id===state.detailId)idx=i;var r=arr[idx]||arr[arr.length-1];if(!r)return wrap(header('記録詳細','','records')+'<div class="content empty">記録がありません</div>'+bottom());state.detailId=r.id;var prev=arr[idx-1],next=arr[idx+1];var s=header('記録の詳細','', 'records');s+='<div class="content"><div class="card"><h2>'+h(r.date)+' '+h(r.time)+'</h2>'+detailRow('食材',r.food)+detailRow('量',r.amount+r.unit)+detailRow('症状',r.symptom?'あり':'なし')+detailRow('皮膚・粘膜','Grade '+r.skin)+detailRow('呼吸器','Grade '+r.resp)+detailRow('消化器','Grade '+r.digest)+detailRow('全身','Grade '+r.whole)+detailRow('使用した薬',r.med)+detailRow('病院受診',r.hospital)+detailRow('症状の詳細',r.detail);if(r.photo){s+='<h3>症状の写真</h3><div class="photo-row"><div class="photo">📷</div><div class="photo">📷</div><div class="photo">📷</div></div>';}s+='<div class="detail-nav"><button class="secondary" '+(prev?'onclick="openDetail('+prev.id+')"':'disabled')+'>← 戻る</button><button class="secondary" '+(next?'onclick="openDetail('+next.id+')"':'disabled')+'>進む →</button></div></div></div>'+bottom();return wrap(s);}
function detailRow(k,v){return '<div class="detail-row"><b>'+h(k)+'</b><span>'+h(v)+'</span></div>';}
function summaryPage(){var foods=['all','卵','牛乳','小麦','ピーナッツ','ナッツ'];var s=header('サマリー','過去の記録をグラフで確認');s+='<div class="content"><div class="card form"><div class="summary-controls"><div><label>表示期間</label><select id="period" onchange="state.period=this.value;render()"><option value="7" '+sel(state.period,'7')+'>7日</option><option value="30" '+sel(state.period,'30')+'>30日</option><option value="90" '+sel(state.period,'90')+'>90日</option></select></div><div><label>食材</label><select id="foodFilter" onchange="state.food=this.value;render()">';for(var i=0;i<foods.length;i++){s+='<option value="'+foods[i]+'" '+sel(state.food,foods[i])+'>'+(foods[i]==='all'?'すべて':foods[i])+'</option>';}s+='</select></div></div></div><div class="card"><div class="section-title">摂取量グラフ</div>'+chartHTML(barData(state.period,state.food),false)+'</div><div class="card"><div class="section-title">症状発生の推移</div>'+symptomTrend()+'</div></div>'+bottom();return wrap(s);}
function symptomTrend(){var data=records.slice().sort(function(a,b){return a.date.localeCompare(b.date);}).slice(-8);var s='<div class="bar-wrap">';for(var i=0;i<data.length;i++){var v=data[i].symptom?1:0;var ht=v?120:25;s+='<div class="bar"><i style="height:'+ht+'px"></i><b>'+data[i].date.slice(5)+'</b><em>'+(v?'症状あり':'なし')+'</em></div>';}return s+'</div>';}
function sel(a,b){return String(a)===String(b)?'selected':'';}
function communityPage(){var allTags=['卵','牛乳','小麦','ピーナッツ','ナッツ','少量摂取','負荷試験','保育園','外食','症状写真','相談','工夫'];var s=header('掲示板','保護者向け安全コミュニティ');s+='<div class="content"><div class="notice">経験共有の場です。診断・治療・摂取量の判断は主治医に相談してください。</div><div class="card"><div class="search"><input id="tagSearch" placeholder="キーワード・タグで検索" value="'+h(state.tag)+'"><button class="primary" onclick="state.tag=document.getElementById(\'tagSearch\').value;render()">検索</button></div><div class="chips" style="margin-top:10px">';for(var i=0;i<allTags.length;i++){s+='<button class="tag '+(state.tag===allTags[i]?'active':'')+'" onclick="state.tag=\''+allTags[i]+'\';render()">#'+allTags[i]+'</button>';}s+='</div></div><div class="card"><div class="link-card"><div class="section-title">投稿一覧</div><button class="primary" onclick="alert(\'投稿作成画面は本番実装で追加します\')">投稿する</button></div>';var shown=0;for(var j=0;j<posts.length;j++){var p=posts[j];var text=(p.title+p.body+p.tags.join(' '));if(state.tag&&text.indexOf(state.tag)<0)continue;shown++;s+='<div class="post"><small>'+h(p.name)+'</small><h3>'+h(p.title)+'</h3><p>'+h(p.body)+'</p><div class="tags">';for(var k=0;k<p.tags.length;k++)s+='<span class="tag">#'+h(p.tags[k])+'</span>';s+='</div><div class="muted">♡ '+p.likes+'　コメント '+p.comments+'</div></div>';}if(!shown)s+='<div class="empty">該当する投稿がありません</div>';s+='</div></div>'+bottom();return wrap(s);}
function settings(){return wrap(header('設定','プロフィール')+'<div class="content"><div class="card"><h2>はるとくんの保護者</h2><div class="record">子ども情報の管理 <span class="right">›</span></div><div class="record">アカウント設定 <span class="right">›</span></div><div class="record">通知設定 <span class="right">›</span></div><div class="record">ヘルプ・よくある質問 <span class="right">›</span></div></div></div>'+bottom());}
function wrap(x){return '<main class="phone">'+x+'</main>';}
function render(){var html='';if(state.page==='home')html=home();else if(state.page==='newRecord')html=newRecord();else if(state.page==='records')html=recordsPage();else if(state.page==='calendar')html=calendarPage();else if(state.page==='detail')html=detailPage();else if(state.page==='community')html=communityPage();else if(state.page==='summary')html=summaryPage();else if(state.page==='settings')html=settings();app.innerHTML=html;}
if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){});});}
render();
})();
