(function(){
'use strict';
var app=document.getElementById('app');
var ALLERGY_FOODS=[
  {name:'卵',icon:'🥚',unit:'g'}, {name:'牛乳',icon:'🥛',unit:'ml'}, {name:'くるみ',icon:'🧠',unit:'g'},
  {name:'小麦',icon:'🌾',unit:'g'}, {name:'ピーナッツ',icon:'🥜',unit:'g'}, {name:'カシューナッツ',icon:'🌙',unit:'g'},
  {name:'えび',icon:'🦐',unit:'g'}, {name:'そば',icon:'🍜',unit:'g'}, {name:'かに',icon:'🦀',unit:'g'}
];
var state={page:'home',detailId:null,editId:null,period:'30',food:'くるみ',symptom:false};
var records=[
{id:1,date:'2026-05-11',time:'18:30',food:'卵',customFood:'',amount:5,unit:'g',symptom:true,skin:1,resp:0,digest:0,whole:0,detail:'口の周りに赤み。30分程度で改善。',med:'抗ヒスタミン薬',hospital:'なし',photo:''},
{id:2,date:'2026-05-10',time:'12:20',food:'牛乳',customFood:'',amount:80,unit:'ml',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'問題なく摂取できました。',med:'なし',hospital:'なし',photo:''},
{id:3,date:'2026-05-09',time:'18:00',food:'くるみ',customFood:'',amount:3,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'症状なし。',med:'なし',hospital:'なし',photo:''},
{id:4,date:'2026-05-08',time:'18:00',food:'その他',customFood:'アーモンド',amount:2,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'その他食材のサンプル記録です。',med:'なし',hospital:'なし',photo:''},
{id:5,date:'2026-05-04',time:'13:00',food:'かに',customFood:'',amount:2,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'記録対象。',med:'なし',hospital:'なし',photo:''}
];
var worries=[
{id:1,date:'2026-05-11',category:'外食',title:'外食時の確認が不安',body:'メニューの確認方法や、少量混入が心配な時の対応を家族で共有したい。'},
{id:2,date:'2026-05-09',category:'継続',title:'週3回の継続が難しい',body:'忙しい日でも無理なく続けられる食べ方をメモしておきたい。'}
];
function save(){try{localStorage.setItem('allergy_records_v4',JSON.stringify(records));localStorage.setItem('allergy_worries_v1',JSON.stringify(worries));}catch(e){}}
function load(){try{var r=localStorage.getItem('allergy_records_v4');if(r)records=JSON.parse(r);var w=localStorage.getItem('allergy_worries_v1');if(w)worries=JSON.parse(w);}catch(e){}}
load();
function h(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function foodName(r){return r.food==='その他'?(r.customFood||'その他'):r.food;}
function foodObj(name){return ALLERGY_FOODS.find(function(f){return f.name===name;})||(name==='その他'?{name:'その他',icon:'✏️',unit:'g'}:{name:name,icon:'●',unit:'g'});}
function nav(page){state.page=page;state.editId=null;if(page!=='detail')state.detailId=null;render();window.scrollTo(0,0);} window.nav=nav;
function openDetail(id){state.page='detail';state.detailId=id;state.editId=null;render();window.scrollTo(0,0);} window.openDetail=openDetail;
function editRecord(id){state.page='edit';state.editId=id;render();window.scrollTo(0,0);} window.editRecord=editRecord;
function wrap(x){return '<main class="phone">'+x+'</main>';}
function header(title,sub,back){return '<div class="top">'+(back?'<button class="iconbtn" onclick="nav(\''+back+'\')">‹</button>':'<img src="./assets/icon-192.png" class="appicon" alt="">')+'<div class="headtext"><div class="title">'+h(title)+'</div><div class="sub">'+h(sub||'')+'</div></div><button class="pillbtn" onclick="nav(\'settings\')">設定</button></div>';}
function bottom(){var items=[['home','🏠','ホーム'],['newRecord','✍️','記録'],['calendar','📅','カレンダー'],['worries','💬','共有']];var s='<div class="bottom">';items.forEach(function(it){s+='<button class="nav '+(state.page===it[0]?'active':'')+'" onclick="nav(\''+it[0]+'\')"><span>'+it[1]+'</span>'+it[2]+'</button>';});return s+'</div>';}
function latest(n){return records.slice().sort(function(a,b){return (b.date+b.time).localeCompare(a.date+a.time);}).slice(0,n||5);}
function weekRange(){var end=new Date('2026-05-11');var day=end.getDay();var diff=(day===0?6:day-1);var start=new Date(end);start.setDate(end.getDate()-diff);return {start:start,end:end};}
function fmt(d){return d.toISOString().slice(0,10);}
function weeklyStatus(){var wr=weekRange(),days={};records.forEach(function(r){var d=new Date(r.date);if(d>=wr.start&&d<=wr.end)days[r.date]=true;});var count=Object.keys(days).length;return {count:count,remain:Math.max(0,3-count)};}
function home(){var w=weeklyStatus();var s=header('アレルギー記録','食べた量・症状・写真を記録');s+='<div class="content"><div class="card hero"><h2>今週の摂取状況</h2><p>目標：週3回以上の摂取</p><div class="goal"><b>'+w.count+'/3回</b><span>'+(w.count>=3?'達成！':'あと'+w.remain+'回')+'</span></div><div class="progress"><i style="width:'+Math.min(100,w.count/3*100)+'%"></i></div><button class="primary full" onclick="nav(\'newRecord\')">＋ 摂取記録を追加</button></div><div class="card link-card" onclick="nav(\'worries\')"><div><div class="section-title">アレルギーの悩み共有</div><div class="muted">困りごと・受診時に相談したいことを記録できます</div></div><b>›</b></div><div class="card"><div class="section-title">最近の記録</div>'+recordList(latest(5))+'</div></div>'+bottom();return wrap(s);}
function recordList(arr){var s='';arr.forEach(function(r){var f=foodObj(r.food);s+='<div class="record" onclick="openDetail('+r.id+')">'+(r.photo?'<img class="thumbMini" src="'+h(r.photo)+'" alt="投稿画像">':'')+'<h3>'+f.icon+' '+h(r.date)+' '+h(foodName(r))+' '+h(r.amount)+h(r.unit)+' <span class="right">›</span></h3><div>'+(r.symptom?'<span class="danger">症状あり</span>':'<span class="safe">症状なし</span>')+'</div><div class="muted">'+h(r.detail)+'</div></div>';});return s||'<div class="empty">記録がありません</div>';}
function foodOptions(selected){var s='';ALLERGY_FOODS.forEach(function(f){s+='<option value="'+f.name+'" '+(selected===f.name?'selected':'')+'>'+f.icon+' '+f.name+'</option>';});s+='<option value="その他" '+(selected==='その他'?'selected':'')+'>✏️ その他</option>';return s;}
function recordForm(mode,r){r=r||{date:'2026-05-11',time:'18:30',food:'卵',customFood:'',amount:1,unit:'g',symptom:false,skin:0,resp:0,digest:0,whole:0,detail:'',med:'なし',hospital:'なし',photo:''};state.symptom=!!r.symptom;var s=header(mode==='edit'?'記録を編集':'摂取記録を入力','',mode==='edit'?'detail':'home');s+='<div class="content"><div class="card form"><label>食べた日時</label><input id="date" type="date" value="'+h(r.date)+'"><input id="time" type="time" value="'+h(r.time)+'"><label>食べた食材</label><select id="food" onchange="toggleOther();syncUnit()">'+foodOptions(r.food)+'</select><div id="otherArea" class="'+(r.food==='その他'?'':'hidden')+'"><label>その他の食材名</label><input id="customFood" value="'+h(r.customFood)+'" placeholder="例：アーモンド、魚、果物など"></div><label>食べた量</label><div class="grid2"><input id="amount" type="number" step="0.1" value="'+h(r.amount)+'"><select id="unit"><option '+(r.unit==='g'?'selected':'')+'>g</option><option '+(r.unit==='ml'?'selected':'')+'>ml</option><option '+(r.unit==='個'?'selected':'')+'>個</option><option '+(r.unit==='口'?'selected':'')+'>口</option></select></div><label>画像を投稿</label><input id="photo" type="file" accept="image/*" onchange="previewPhoto(event)"><img id="photoPreview" class="thumb '+(r.photo?'':'hidden')+'" src="'+h(r.photo||'')+'" alt="投稿画像プレビュー"><label>症状はありましたか？</label><div class="seg"><button id="noBtn" class="'+(!r.symptom?'on':'')+'" onclick="setSym(false);return false">😊 なし</button><button id="yesBtn" class="'+(r.symptom?'bad':'')+'" onclick="setSym(true);return false">😟 あり</button></div><div id="symArea" class="'+(r.symptom?'':'hidden')+'">'+grade('皮膚・粘膜','skin',r.skin)+grade('呼吸器','resp',r.resp)+grade('消化器','digest',r.digest)+grade('全身','whole',r.whole)+'<label>使用した薬</label><input id="med" value="'+h(r.med)+'" placeholder="例：抗ヒスタミン薬"><label>病院受診</label><input id="hospital" value="'+h(r.hospital)+'" placeholder="例：なし、救急外来"><label>症状の詳細</label><textarea id="detail" placeholder="例：口の周りに赤み">'+h(r.detail)+'</textarea></div><button class="primary full" onclick="'+(mode==='edit'?'updateRecord()':'addRecord()')+'">保存する</button></div></div>'+bottom();return wrap(s);}
function grade(label,id,v){return '<div class="grade"><b>'+label+'</b><select id="'+id+'"><option value="0" '+(v==0?'selected':'')+'>Grade 0</option><option value="1" '+(v==1?'selected':'')+'>Grade 1</option><option value="2" '+(v==2?'selected':'')+'>Grade 2</option><option value="3" '+(v==3?'selected':'')+'>Grade 3</option></select></div>';}
window.toggleOther=function(){var el=document.getElementById('otherArea');if(el)el.className=val('food')==='その他'?'':'hidden';};
window.syncUnit=function(){var f=foodObj(val('food'));var unit=document.getElementById('unit');if(unit&&val('food')!=='その他')unit.value=f.unit;};
window.setSym=function(v){state.symptom=v;document.getElementById('symArea').className=v?'':'hidden';document.getElementById('noBtn').className=v?'':'on';document.getElementById('yesBtn').className=v?'bad':'';};
window.previewPhoto=function(e){var file=e.target.files&&e.target.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){var img=document.getElementById('photoPreview');img.src=reader.result;img.className='thumb';};reader.readAsDataURL(file);};
function val(id){var el=document.getElementById(id);return el?el.value:'';}
function collectRecord(old){var photoEl=document.getElementById('photoPreview');return {id:old&&old.id?old.id:Date.now(),date:val('date'),time:val('time'),food:val('food'),customFood:val('food')==='その他'?val('customFood'):'',amount:Number(val('amount')),unit:val('unit'),symptom:state.symptom,skin:Number(val('skin')||0),resp:Number(val('resp')||0),digest:Number(val('digest')||0),whole:Number(val('whole')||0),detail:val('detail')||'記録しました。',med:val('med')||'なし',hospital:val('hospital')||'なし',photo:(photoEl&&!photoEl.className.includes('hidden'))?photoEl.src:(old?old.photo:'')};}
window.addRecord=function(){var rec=collectRecord(null);records.push(rec);save();openDetail(rec.id);};
window.updateRecord=function(){var i=records.findIndex(function(x){return x.id===state.editId;});if(i<0)return;records[i]=collectRecord(records[i]);state.detailId=records[i].id;save();openDetail(records[i].id);};
window.deleteRecord=function(id){if(!confirm('この記録を削除しますか？'))return;records=records.filter(function(r){return r.id!==id;});save();nav('home');};
function calendarPage(){var s=header('カレンダー','その他の食材名も表示');s+='<div class="content"><div class="card"><div class="link-card"><button class="iconbtn">‹</button><div class="section-title">2026年5月</div><button class="iconbtn">›</button></div><table class="calendar"><thead><tr>';['月','火','水','木','金','土','日'].forEach(function(d){s+='<th>'+d+'</th>';});s+='</tr></thead><tbody>';var day=1;for(var w=0;w<5;w++){s+='<tr>';for(var c=0;c<7;c++){if((w===0&&c<4)||day>31){s+='<td></td>';continue;}var ds='2026-05-'+(day<10?'0'+day:day);var rs=records.filter(function(r){return r.date===ds;});s+='<td class="'+(rs.length?'has':'')+'" '+(rs[0]?'onclick="openDetail('+rs[0].id+')"':'')+'><b>'+day+'</b><div class="icons">';rs.slice(0,2).forEach(function(r){s+='<span>'+foodObj(r.food).icon+'</span>';});s+='</div><div class="calfood">'+rs.slice(0,2).map(foodName).map(h).join('、')+'</div></td>';day++;}s+='</tr>';}s+='</tbody></table><div class="legend">';ALLERGY_FOODS.concat([{name:'その他',icon:'✏️'}]).forEach(function(f){s+='<span>'+f.icon+' '+f.name+'</span>';});s+='</div></div></div>'+bottom();return wrap(s);}
function detailPage(){var r=records.find(function(x){return x.id===state.detailId;});if(!r)return wrap(header('記録詳細','','home')+'<div class="content empty">記録がありません</div>'+bottom());var s=header('記録の詳細','編集・削除ができます','home');s+='<div class="content"><div class="card"><h2>'+foodObj(r.food).icon+' '+h(r.date)+' '+h(r.time)+'</h2>'+(r.photo?'<img class="thumb" src="'+h(r.photo)+'" alt="投稿画像">':'')+detailRow('食材',foodName(r))+detailRow('量',r.amount+r.unit)+detailRow('症状',r.symptom?'あり':'なし')+detailRow('最大Grade',Math.max(r.skin,r.resp,r.digest,r.whole))+detailRow('使用した薬',r.med)+detailRow('病院受診',r.hospital)+detailRow('症状の詳細',r.detail)+'<div class="actions"><button class="primary" onclick="editRecord('+r.id+')">編集</button><button class="dangerBtn" onclick="deleteRecord('+r.id+')">削除</button></div></div></div>'+bottom();return wrap(s);}
function detailRow(k,v){return '<div class="detail-row"><b>'+h(k)+'</b><span>'+h(v)+'</span></div>';}
function worriesPage(){var s=header('悩み共有','相談したいことをメモ');s+='<div class="content"><div class="card form"><label>カテゴリー</label><select id="wCategory"><option>外食</option><option>園・学校</option><option>家庭</option><option>継続</option><option>受診相談</option><option>その他</option></select><label>タイトル</label><input id="wTitle" placeholder="例：旅行中の食事が不安"><label>内容</label><textarea id="wBody" placeholder="悩み、工夫、医師に聞きたいことを記録"></textarea><button class="primary full" onclick="addWorry()">共有メモを追加</button><p class="small">※このサンプル版では端末内に保存されます。実運用で家族・医師と共有する場合は、ログインやサーバー保存を追加してください。</p></div><div class="card"><div class="section-title">共有メモ一覧</div>'+worryList()+'</div></div>'+bottom();return wrap(s);}
function worryList(){return worries.slice().sort(function(a,b){return b.id-a.id;}).map(function(w){return '<div class="topic"><span class="tag">'+h(w.category)+'</span><span class="muted">'+h(w.date)+'</span><h3>'+h(w.title)+'</h3><p class="muted">'+h(w.body)+'</p></div>';}).join('')||'<div class="empty">共有メモはまだありません</div>';}
window.addWorry=function(){var title=val('wTitle'),body=val('wBody');if(!title&&!body)return alert('タイトルまたは内容を入力してください');worries.push({id:Date.now(),date:new Date().toISOString().slice(0,10),category:val('wCategory'),title:title||'無題',body:body||''});save();render();};
function settings(){return wrap(header('設定','')+'<div class="content"><div class="card"><h2>設定</h2><p class="muted">PWA対応。GitHub Pagesではこのフォルダ一式をアップロードしてください。</p></div></div>'+bottom());}
function render(){var html='';if(state.page==='home')html=home();else if(state.page==='newRecord')html=recordForm('new');else if(state.page==='calendar')html=calendarPage();else if(state.page==='detail')html=detailPage();else if(state.page==='edit')html=recordForm('edit',records.find(function(x){return x.id===state.editId;}));else if(state.page==='worries')html=worriesPage();else if(state.page==='settings')html=settings();app.innerHTML=html;}
if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){});});}
render();
})();
